name: ci_python

on:
  push:
    paths:
    - "**.py"
  pull_request:
    paths:
    - "**.py"

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install .[lint]
    - run: flake8
    - run: mypy .
